name: wrapartist
favicon: null
layout_spectrum: 0.7278595506213605
typography_spectrum: 0.3595427165273577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#c8c7c7'
    - '#7f7c7d'
    - '#565354'
  brandStrength: 1
  lightness: 0.2920595386531204
  saturation: 0.8523983298800886
  rhythmicContrast: 0.6084775989875197
purpose: []
